---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины 
  - Пользователь должен иметь возможность оформить заказ
  - Пользователь должен иметь возможность оплатить заказ
  - Пользователь должен иметь возможность удаления товаров из корзины
  - Содержимое корзины должно храниться в сессии браузера
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Корректное отображение списка категорий
  - Корректное отображение списка брэндов согласно выбранной категории
  - При переключении страницы нажатием кнопки "Next" в нижней части страницы должно перемещать в начало страницы
implicit:
  - Отображение отфильтрованных товаров должно показываться постранично
  - Корректное отображение цен и кнопки добавления товара в корзину на странице просмотра
